include:
  # - board: nice_nano_v2
  #   shield: charybdis_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: charybdis_dongle nice_view_adapter dongle_display
    artifact-name: charybdis_dongle_nice_view


  - board: nice_nano_v2
    shield: charybdis_left

  - board: nice_nano_v2
    shield: charybdis_right
    # snippet: zmk-usb-logging
    # cmake-args: -DCONFIG_ZMK_USB_LOGGING=y

  - board: nice_nano_v2
    shield: charybdis_right_central

  # - board: nice_nano_v2
  #   shield: settings_reset

