
# B) ALTERNATIVE: NO LATENCY (snappiest, but higher battery use)
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y
# 9 * 1.25ms = 11.25 ms
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=9
# 12 * 1.25ms = 15.00 ms
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
# attend every interval, no skipping
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
# 4.0 s
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400